### ISSUE TITLE
How to get the answer back?

### ISSUE THREAD

**Issue by Areij1** [sid-sundrani/differentiable-kb-qa#1]
I see that there is no way to get the natural language answer back after a prediction. Can you please help point out how this can be done?

**Comment by sidhantls** [comment]
Depends on what you mean. If you are asking if there is a way to get the actual answer entities in string format for a given question, you can do that. This notebook should help you - https://github.com/sidhantls/differentiable-kb-qa/blob/master/kgqa/models/test_predict.ipynb

Does this answer your question?

**Comment by Areij1** [comment]
Yup that's what exactly what I was asking for. Thanks!
